version: '3'
services:
  web:
    build: .
    command: >
      bash -c "rm /myapp/tmp/pids/server.pid
      && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./myapp:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mysql:8.0.12
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"